version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    container_name: eureka-server
    networks:
      - ecommerce-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    container_name: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    container_name: order-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  payment-service:
    build: ./payment-service
    ports:
      - "8082:8082"
    container_name: payment-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  product-service:
    build: ./product-service
    ports:
      - "8083:8083"
    container_name: product-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8084:8084"
    container_name: inventory-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

  user-service:
    build: ./user-service
    ports:
      - "8085:8085"
    container_name: user-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
