server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**

            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

