server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://order-db:5432/users
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
